services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - /usr/local/cargo/registry
      - /app/target
    env_file:
      - ".env"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./database/:var/lib/postgresql/:delegated
    env_file:
      - ".env"
